max_width = 100
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Off"
indent_style = "Visual"
wrap_comments = false
format_code_in_doc_comments = false
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true
license_template_path = ""
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
empty_item_single_line = false
struct_lit_single_line = false
fn_single_line = false
where_single_line = true
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "Preserve"
reorder_imports = false
reorder_modules = false
reorder_impl_items = false
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = false
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
force_multiline_blocks = true
fn_args_layout = "Tall"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition = "2021"
version = "One"
inline_attribute_width = 0
merge_derives = false
use_try_shorthand = true
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = false
color = "Auto"
required_version = "1.4.37"
unstable_features = true
disable_all_formatting = true
skip_children = false
hide_parse_errors = false
error_on_line_overflow = true
error_on_unformatted = true
report_todo = "Always"
report_fixme = "Always"
ignore = []
emit_mode = "Files"
make_backup = false
